import reflex as rx
import TeleLisa.styles.styles as styles


def season_menu() -> rx.Component:
    return rx.box(
        rx.hstack(
            rx.link(
                rx.text("T1"), 
                href="#",
            ),
            rx.link(
                rx.text("T2"), 
                href="#",
            ),
            rx.link(
                rx.text("T3"), 
                href="#",
            ),
            rx.link(
                rx.text("T4"), 
                href="#",
            ),
            rx.link(
                rx.text("T5"), 
                href="#",
            ),
            rx.link(
                rx.text("T6"), 
                href="#",
            ),
            rx.link(
                rx.text("T7"), 
                href="#",
            ),
            rx.link(
                rx.text("T8"), 
                href="#",
            ),
            rx.link(
                rx.text("T9"), 
                href="#",
            ),
            rx.link(
                rx.text("T10"), 
                href="#",
            ),
            rx.link(
                rx.text("T11"), 
                href="#",
            ),
            rx.link(
                rx.text("T12"), 
                href="#",
            ),
            rx.link(
                rx.text("T13"), 
                href="#",
            ),
            rx.link(
                rx.text("T14"), 
                href="#",
            ),
            rx.link(
                rx.text("T15"), 
                href="#",
            ),
            rx.link(
                rx.text("T16"), 
                href="#",
            ),
            rx.link(
                rx.text("T17"), 
                href="#",
            ),
            rx.link(
                rx.text("T18"), 
                href="#",
            ),
            rx.link(
                rx.text("T19"), 
                href="#",
            ),
            rx.link(
                rx.text("T20"), 
                href="#",
            ),
            justify="between",
            align="center",
            style=styles.season_menu.menu_style
        )
    )